### ISSUE TITLE
Game crashes if saved player is not in a tournament

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#490] opened 2023-06-03 11:20 UTC
If last played (and saved) tournament player is not in any tournament and you punch the "tournament" button in the main menu, the game crashes.

**Comment by mrannanj** [comment] 2024-07-27 11:58
I could not reproduce this via the game, did you edit CHR file yourself to get this?

**Comment by mrannanj** [comment] 2024-08-30 02:51
Fixed by #550

**Closed by mrannanj** 2024-08-30 02:51 UTC
Labels: bug
